#!/usr/bin/env python
import sys
import zabbix_api

hostname=sys.argv[1];
url=sys.argv[2];
user=sys.argv[3];
passwd=sys.argv[4];
pskID=sys.argv[5];
pskKey=sys.argv[6];
group_name="Gruppo Prova"
zapi = zabbix_api.ZabbixAPI(url=url, user=user,password=passwd)
#res1 = zapi.do_request('host.get', { 'filter': {'name': hostname}}) #, 'output': 'hostid'
#res1= zapi.host.get(hostids=sys.argv[1] , output=['hostid'])
#print res1
#res2 = str(res1.get(u'result')).split('\'')
#zabbix_hostid = res2[3]
#zapi.do_request('host.update', {'hostid': 0, 'tls_psk': sys.argv[6]})